### ISSUE TITLE
ImportScoreActivity类中发生了运行时异常

### ISSUE THREAD

**Issue by nethcx** [sasaju/NormalSchedule#6]
使用侧边栏的成绩查询等功能会发生此问题
可能仅在8gen1往上这种新架构的处理器上会发生

java.lang.RuntimeException: Unable to start activity ComponentInfo{com.liflymark.normalschedule/com.liflymark.normalschedule.ui.imort_show_score.ImportScoreActivity}: com.google.crypto.tink.shaded.protobuf.z: Protocol message contained an invalid tag (zero).
	at android.app.ActivityThread.performLaunchActivity(ActivityThread.java:3817)
	at android.app.ActivityThread.handleLaunchActivity(ActivityThread.java:3963)
	at android.app.servertransaction.LaunchActivityItem.execute(LaunchActivityItem.java:101)
	at android.app.servertransaction.TransactionExecutor.executeCallbacks(TransactionExecutor.java:135)
	at android.app.servertransaction.TransactionExecutor.execute(TransactionExecutor.java:95)
	at android.app.ActivityThread$H.handleMessage(ActivityThread.java:2381)
	at android.os.Handler.dispatchMessage(Handler.java:106)
	at android.os.Looper.loopOnce(Looper.java:210)
	at android.os.Looper.loop(Looper.java:299)
	at android.app.ActivityThread.main(ActivityThread.java:8247)
	at java.lang.reflect.Method.invoke(Native Method)
	at com.android.internal.os.RuntimeInit$MethodAndArgsCaller.run(RuntimeInit.java:559)
	at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:954)
Caused by: com.google.crypto.tink.shaded.protobuf.z: Protocol message contained an invalid tag (zero).
	at com.google.crypto.tink.shaded.protobuf.e.F(SourceFile:157)
	at com.google.crypto.tink.shaded.protobuf.s0.C(SourceFile:756)
	at com.google.crypto.tink.shaded.protobuf.s0.i(Unknown Source:4)
	at com.google.crypto.tink.shaded.protobuf.e.o(Unknown Source:28)
	at com.google.crypto.tink.shaded.protobuf.e.p(Unknown Source:0)
	at com.google.crypto.tink.shaded.protobuf.s0.C(SourceFile:554)
	at com.google.crypto.tink.shaded.protobuf.s0.i(Unknown Source:4)
	at com.google.crypto.tink.shaded.protobuf.w.o(SourceFile:34)
	at r8.c0.z(Unknown Source:2)
	at l8.a$a.a(SourceFile:56)
	at f9.c.b(SourceFile:99)
	at e9.a.i(SourceFile:21)
	at com.liflymark.normalschedule.ui.import_show_score.ImportScoreActivity.onCreate(SourceFile:299)
	at android.app.Activity.performCreate(Activity.java:8508)
	at android.app.Activity.performCreate(Activity.java:8472)
	at android.app.Instrumentation.callActivityOnCreate(Instrumentation.java:1418)
	at android.app.ActivityThread.performLaunchActivity(ActivityThread.java:3798)
	... 12 more

**Comment by sasaju** [comment]
能提供手机型号和复现方式吗？一点就会闪退吗，侧边栏所有功能都会这样吗？

**Comment by nethcx** [comment]
app为0.3.1，型号为k60 安卓13 8gen1+ 侧边栏的成绩查询一点击就闪退会桌面 本学期成绩查询则是概率性，尝试很多次可以进入一次，不成功的情况和考试安排一样，而考试安排是输入学号密码点击查询后直接回到应用主界面

**Comment by nethcx** [comment]
![Screenrecorder-2023-06-12-14-05-37-485](https://github.com/sasaju/NormalSchedule/assets/64411236/e5188949-b358-42f8-94a1-331b423cf0e0)
像这样，拿手上的老设备试了一下功能都是正常的

**Comment by sasaju** [comment]
我这里初步测试也有问题，我这里的问题是k60登录不上，我排查一下。如果不介意的话可以加一下反馈群

**Comment by sasaju** [comment]
这个问题可以清除一下缓存试试。如果是其他设备迁移过来的，需要清除数据。
这个Bug的原因应该是加密密码读取失败导致的。
如果清除数据还是不行请再回复

**Comment by nethcx** [comment]
确实是,没想到是迁移的问题
